{
  "uid" : "38cf0b32c6a7a8e1",
  "name" : "User can't transfer funds leaving amount field empty",
  "fullName" : "tests.core_features.test_funds_transfer.TestFundsTransfer#test_funds_transfer_with_empty_amount",
  "historyId" : "5d72f60001d4c80e4581c8fae63d198e",
  "time" : {
    "start" : 1704908682718,
    "stop" : 1704908682718,
    "duration" : 0
  },
  "status" : "skipped",
  "statusMessage" : "XFAIL reason: Health check failed with status code 502\n\n_pytest.outcomes.XFailed: Health check failed with status code 502",
  "statusTrace" : "conftest.py:32: in health_check\n    pytest.xfail(reason=f\"Health check failed with status code {response.status_code}\")\nE   _pytest.outcomes.XFailed: Health check failed with status code 502\n        response   = <Response [502]>\n        url        = 'https://parabank.parasoft.com/parabank'",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "Health check request",
    "time" : {
      "start" : 1704908682351,
      "stop" : 1704908682639,
      "duration" : 288
    },
    "status" : "failed",
    "statusMessage" : "_pytest.outcomes.XFailed: Health check failed with status code 502\n",
    "statusTrace" : "  File \"/usr/local/lib/python3.11/site-packages/pluggy/_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/workspace/conftest.py\", line 32, in health_check\n    pytest.xfail(reason=f\"Health check failed with status code {response.status_code}\")\n  File \"/usr/local/lib/python3.11/site-packages/_pytest/outcomes.py\", line 256, in xfail\n    raise XFailed(reason)\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "stepsCount" : 0,
    "hasContent" : true
  }, {
    "name" : "_session_faker",
    "time" : {
      "start" : 1704908682330,
      "stop" : 1704908682350,
      "duration" : 20
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  } ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "feature",
    "value" : "PARA-15270: Funds transfer"
  }, {
    "name" : "epic",
    "value" : "PARA-15242: Funds operations"
  }, {
    "name" : "severity",
    "value" : "Minor"
  }, {
    "name" : "parentSuite",
    "value" : "tests.core_features"
  }, {
    "name" : "suite",
    "value" : "test_funds_transfer"
  }, {
    "name" : "subSuite",
    "value" : "TestFundsTransfer"
  }, {
    "name" : "host",
    "value" : "457bd63967c0"
  }, {
    "name" : "thread",
    "value" : "1-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.core_features.test_funds_transfer"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "minor",
    "retries" : [ ],
    "categories" : [ ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 1,
        "skipped" : 1,
        "passed" : 4,
        "unknown" : 0,
        "total" : 6
      },
      "items" : [ {
        "uid" : "2be7a4e3452ef000",
        "status" : "passed",
        "time" : {
          "start" : 1704874961761,
          "stop" : 1704874967148,
          "duration" : 5387
        }
      }, {
        "uid" : "22c7579b3adc13f0",
        "status" : "passed",
        "time" : {
          "start" : 1704839519492,
          "stop" : 1704839541356,
          "duration" : 21864
        }
      }, {
        "uid" : "8d53e8b31d6fe83f",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found\n  (Session info: headless chrome=119.0.6045.159); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception",
        "time" : {
          "start" : 1704789353115,
          "stop" : 1704789355175,
          "duration" : 2060
        }
      }, {
        "uid" : "90268d5bbc49fc93",
        "status" : "passed",
        "time" : {
          "start" : 1704759021274,
          "stop" : 1704759025947,
          "duration" : 4673
        }
      }, {
        "uid" : "117c3fb2cbcbf3db",
        "status" : "passed",
        "time" : {
          "start" : 1704756560139,
          "stop" : 1704756565432,
          "duration" : 5293
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "38cf0b32c6a7a8e1.json",
  "parameterValues" : [ ]
}