{
  "uid" : "5e7dcbff4cf558ab",
  "name" : "User can't successfully log in with invalid password.",
  "fullName" : "tests.core_features.test_login.TestLogin#test_login_with_invalid_password",
  "historyId" : "0ca18d8bd97e96e2fad3ec13e04117a8",
  "time" : {
    "start" : 1705147649692,
    "stop" : 1705147666962,
    "duration" : 17270
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.TimeoutException: Message:",
  "statusTrace" : "tests/core_features/test_login.py:50: in test_login_with_invalid_password\n    login_page.error_text.assert_error(\"The username and password could not be verified.\")\n        driver     = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"63a79331f0a5bab73ff9daa5d4e8535f\")>\n        home_page  = <src.pages.home_page.HomePage object at 0x7fdbd6c6ed90>\n        login_page = <src.pages.login_page.LoginPage object at 0x7fdbd6c6d410>\n        self       = <test_login.TestLogin object at 0x7fdbd3b934d0>\nsrc/base/base_element.py:69: in assert_error\n    current_error = self.get_text()\n        expected_error = 'The username and password could not be verified.'\n        self       = <src.base.base_element.BaseElement object at 0x7fdbd548d810>\n        server_error = 'An internal error has occurred and has been logged.'\nsrc/base/base_element.py:37: in get_text\n    element = self.assert_element()\n        self       = <src.base.base_element.BaseElement object at 0x7fdbd548d810>\nsrc/base/base_element.py:16: in assert_element\n    self.wait.until(EC.presence_of_element_located((\"xpath\", self.xpath)))\n        clickable  = False\n        return_many = False\n        self       = <src.base.base_element.BaseElement object at 0x7fdbd548d810>\n../local/lib/python3.11/site-packages/selenium/webdriver/support/wait.py:101: in until\n    raise TimeoutException(message, screen, stacktrace)\nE   selenium.common.exceptions.TimeoutException: Message:\n        end_time   = 321.181822643\n        message    = ''\n        method     = <function presence_of_element_located.<locals>._predicate at 0x7fdbd6c20900>\n        screen     = None\n        self       = <selenium.webdriver.support.wait.WebDriverWait (session=\"63a79331f0a5bab73ff9daa5d4e8535f\")>\n        stacktrace = None",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "Health check request",
    "time" : {
      "start" : 1705147517847,
      "stop" : 1705147518594,
      "duration" : 747
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "_session_faker",
    "time" : {
      "start" : 1705147517826,
      "stop" : 1705147517847,
      "duration" : 21
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "Initialize driver",
    "time" : {
      "start" : 1705147648853,
      "stop" : 1705147649691,
      "duration" : 838
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.TimeoutException: Message:",
    "statusTrace" : "tests/core_features/test_login.py:50: in test_login_with_invalid_password\n    login_page.error_text.assert_error(\"The username and password could not be verified.\")\n        driver     = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"63a79331f0a5bab73ff9daa5d4e8535f\")>\n        home_page  = <src.pages.home_page.HomePage object at 0x7fdbd6c6ed90>\n        login_page = <src.pages.login_page.LoginPage object at 0x7fdbd6c6d410>\n        self       = <test_login.TestLogin object at 0x7fdbd3b934d0>\nsrc/base/base_element.py:69: in assert_error\n    current_error = self.get_text()\n        expected_error = 'The username and password could not be verified.'\n        self       = <src.base.base_element.BaseElement object at 0x7fdbd548d810>\n        server_error = 'An internal error has occurred and has been logged.'\nsrc/base/base_element.py:37: in get_text\n    element = self.assert_element()\n        self       = <src.base.base_element.BaseElement object at 0x7fdbd548d810>\nsrc/base/base_element.py:16: in assert_element\n    self.wait.until(EC.presence_of_element_located((\"xpath\", self.xpath)))\n        clickable  = False\n        return_many = False\n        self       = <src.base.base_element.BaseElement object at 0x7fdbd548d810>\n../local/lib/python3.11/site-packages/selenium/webdriver/support/wait.py:101: in until\n    raise TimeoutException(message, screen, stacktrace)\nE   selenium.common.exceptions.TimeoutException: Message:\n        end_time   = 321.181822643\n        message    = ''\n        method     = <function presence_of_element_located.<locals>._predicate at 0x7fdbd6c20900>\n        screen     = None\n        self       = <selenium.webdriver.support.wait.WebDriverWait (session=\"63a79331f0a5bab73ff9daa5d4e8535f\")>\n        stacktrace = None",
    "steps" : [ {
      "name" : "Navigate to Home page",
      "time" : {
        "start" : 1705147649692,
        "stop" : 1705147650666,
        "duration" : 974
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "Fill in valid username, but invalid password",
      "time" : {
        "start" : 1705147650666,
        "stop" : 1705147650829,
        "duration" : 163
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "Log in",
      "time" : {
        "start" : 1705147650829,
        "stop" : 1705147651755,
        "duration" : 926
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "Check error message is displayed",
      "time" : {
        "start" : 1705147651755,
        "stop" : 1705147666961,
        "duration" : 15206
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.TimeoutException: Message: \n\n",
      "statusTrace" : "  File \"/usr/workspace/tests/core_features/test_login.py\", line 50, in test_login_with_invalid_password\n    login_page.error_text.assert_error(\"The username and password could not be verified.\")\n  File \"/usr/workspace/src/base/base_element.py\", line 69, in assert_error\n    current_error = self.get_text()\n                    ^^^^^^^^^^^^^^^\n  File \"/usr/workspace/src/base/base_element.py\", line 37, in get_text\n    element = self.assert_element()\n              ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/workspace/src/base/base_element.py\", line 16, in assert_element\n    self.wait.until(EC.presence_of_element_located((\"xpath\", self.xpath)))\n  File \"/usr/local/lib/python3.11/site-packages/selenium/webdriver/support/wait.py\", line 101, in until\n    raise TimeoutException(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 4,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ {
    "name" : "Initialize driver::0",
    "time" : {
      "start" : 1705147666969,
      "stop" : 1705147667028,
      "duration" : 59
    },
    "status" : "passed",
    "steps" : [ {
      "name" : "Terminate driver",
      "time" : {
        "start" : 1705147666969,
        "stop" : 1705147667028,
        "duration" : 59
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "PARA-15240: User registration and authentication"
  }, {
    "name" : "feature",
    "value" : "PARA-15261: User login"
  }, {
    "name" : "severity",
    "value" : "Minor"
  }, {
    "name" : "parentSuite",
    "value" : "tests.core_features"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "subSuite",
    "value" : "TestLogin"
  }, {
    "name" : "host",
    "value" : "fdd3900bcbbf"
  }, {
    "name" : "thread",
    "value" : "1-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.core_features.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "minor",
    "retries" : [ {
      "uid" : "8ba706878273a791",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.TimeoutException: Message:",
      "time" : {
        "start" : 1705147631883,
        "stop" : 1705147648784,
        "duration" : 16901
      }
    }, {
      "uid" : "f7170f6512a4205b",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.TimeoutException: Message:",
      "time" : {
        "start" : 1705147613702,
        "stop" : 1705147630981,
        "duration" : 17279
      }
    }, {
      "uid" : "700fd2c5aef3cc45",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.TimeoutException: Message:",
      "time" : {
        "start" : 1705147595815,
        "stop" : 1705147612796,
        "duration" : 16981
      }
    } ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 1,
        "skipped" : 7,
        "passed" : 1,
        "unknown" : 0,
        "total" : 9
      },
      "items" : [ {
        "uid" : "e190f26f7214f7d0",
        "status" : "passed",
        "time" : {
          "start" : 1705016480476,
          "stop" : 1705016481711,
          "duration" : 1235
        }
      }, {
        "uid" : "e04b62efc34bb97d",
        "status" : "skipped",
        "statusDetails" : "XFAIL reason: Known server-side issue\n\n_pytest.outcomes.XFailed: Known server-side issue",
        "time" : {
          "start" : 1704913007085,
          "stop" : 1704913007821,
          "duration" : 736
        }
      }, {
        "uid" : "34036144644cbdca",
        "status" : "skipped",
        "statusDetails" : "XFAIL reason: Health check failed with status code 502\n\n_pytest.outcomes.XFailed: Health check failed with status code 502",
        "time" : {
          "start" : 1704908682724,
          "stop" : 1704908682724,
          "duration" : 0
        }
      }, {
        "uid" : "bf6294b63c28caed",
        "status" : "skipped",
        "statusDetails" : "XFAIL reason: Known server-side issue\n\n_pytest.outcomes.XFailed: Known server-side issue",
        "time" : {
          "start" : 1704874970180,
          "stop" : 1704874971491,
          "duration" : 1311
        }
      }, {
        "uid" : "d87ec95d2bd7a1d7",
        "status" : "skipped",
        "statusDetails" : "XFAIL reason: Known server-side issue\n\n_pytest.outcomes.XFailed: Known server-side issue",
        "time" : {
          "start" : 1704839544422,
          "stop" : 1704839545491,
          "duration" : 1069
        }
      }, {
        "uid" : "ceab7a397b75762c",
        "status" : "skipped",
        "statusDetails" : "XFAIL reason: Known server-side issue\n\n_pytest.outcomes.XFailed: Known server-side issue",
        "time" : {
          "start" : 1704789358098,
          "stop" : 1704789359199,
          "duration" : 1101
        }
      }, {
        "uid" : "bb142fe10b5e53ec",
        "status" : "skipped",
        "statusDetails" : "XFAIL reason: Known server-side issue\n\n_pytest.outcomes.XFailed: Known server-side issue",
        "time" : {
          "start" : 1704759028518,
          "stop" : 1704759029330,
          "duration" : 812
        }
      }, {
        "uid" : "cce9cde06874d2bf",
        "status" : "skipped",
        "statusDetails" : "XFAIL reason: Known server-side issue\n\n_pytest.outcomes.XFailed: Known server-side issue",
        "time" : {
          "start" : 1704756568705,
          "stop" : 1704756570047,
          "duration" : 1342
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "5e7dcbff4cf558ab.json",
  "parameterValues" : [ ]
}