{
  "uid" : "9eb001e083d3b82b",
  "name" : "User can successfully open a new account of 'Checking' type.",
  "fullName" : "tests.core_features.test_new_account_opening.TestNewAccountOpening#test_new_checking_account_opening",
  "historyId" : "595505eab70eb0d9ff6d35befc70f62b",
  "time" : {
    "start" : 1704908682735,
    "stop" : 1704908682735,
    "duration" : 0
  },
  "status" : "skipped",
  "statusMessage" : "XFAIL reason: Health check failed with status code 502\n\n_pytest.outcomes.XFailed: Health check failed with status code 502",
  "statusTrace" : "conftest.py:32: in health_check\n    pytest.xfail(reason=f\"Health check failed with status code {response.status_code}\")\nE   _pytest.outcomes.XFailed: Health check failed with status code 502\n        response   = <Response [502]>\n        url        = 'https://parabank.parasoft.com/parabank'",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "Health check request",
    "time" : {
      "start" : 1704908682351,
      "stop" : 1704908682639,
      "duration" : 288
    },
    "status" : "failed",
    "statusMessage" : "_pytest.outcomes.XFailed: Health check failed with status code 502\n",
    "statusTrace" : "  File \"/usr/local/lib/python3.11/site-packages/pluggy/_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/workspace/conftest.py\", line 32, in health_check\n    pytest.xfail(reason=f\"Health check failed with status code {response.status_code}\")\n  File \"/usr/local/lib/python3.11/site-packages/_pytest/outcomes.py\", line 256, in xfail\n    raise XFailed(reason)\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "stepsCount" : 0,
    "hasContent" : true
  }, {
    "name" : "_session_faker",
    "time" : {
      "start" : 1704908682330,
      "stop" : 1704908682350,
      "duration" : 20
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  } ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "epic",
    "value" : "PARA-15241: Account operations"
  }, {
    "name" : "feature",
    "value" : "PARA-15252: New account opening"
  }, {
    "name" : "severity",
    "value" : "Critical"
  }, {
    "name" : "tag",
    "value" : "smoke"
  }, {
    "name" : "parentSuite",
    "value" : "tests.core_features"
  }, {
    "name" : "suite",
    "value" : "test_new_account_opening"
  }, {
    "name" : "subSuite",
    "value" : "TestNewAccountOpening"
  }, {
    "name" : "host",
    "value" : "457bd63967c0"
  }, {
    "name" : "thread",
    "value" : "1-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.core_features.test_new_account_opening"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "critical",
    "retries" : [ ],
    "categories" : [ ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 1,
        "skipped" : 1,
        "passed" : 4,
        "unknown" : 0,
        "total" : 6
      },
      "items" : [ {
        "uid" : "34fefa46f5c85c16",
        "status" : "passed",
        "time" : {
          "start" : 1704874979092,
          "stop" : 1704874982507,
          "duration" : 3415
        }
      }, {
        "uid" : "212f754996594779",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found\n  (Session info: headless chrome=119.0.6045.159); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception",
        "time" : {
          "start" : 1704839559752,
          "stop" : 1704839561102,
          "duration" : 1350
        }
      }, {
        "uid" : "111037e6b742de6e",
        "status" : "passed",
        "time" : {
          "start" : 1704789365766,
          "stop" : 1704789368995,
          "duration" : 3229
        }
      }, {
        "uid" : "5696e0eefcbe5142",
        "status" : "passed",
        "time" : {
          "start" : 1704759035209,
          "stop" : 1704759037548,
          "duration" : 2339
        }
      }, {
        "uid" : "170975122fabee2a",
        "status" : "passed",
        "time" : {
          "start" : 1704756577227,
          "stop" : 1704756580678,
          "duration" : 3451
        }
      } ]
    },
    "tags" : [ "smoke" ]
  },
  "source" : "9eb001e083d3b82b.json",
  "parameterValues" : [ ]
}