{
  "uid" : "f112a86e48f5a304",
  "name" : "User can't successfully log in with invalid username.",
  "fullName" : "tests.core_features.test_login.TestLogin#test_login_with_invalid_username",
  "historyId" : "d9da1d35f9d1a309fb04ddfe89a222bc",
  "time" : {
    "start" : 1705147722132,
    "stop" : 1705147739232,
    "duration" : 17100
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.TimeoutException: Message:",
  "statusTrace" : "tests/core_features/test_login.py:69: in test_login_with_invalid_username\n    login_page.error_text.assert_error(\"The username and password could not be verified.\")\n        driver     = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"a23ea4b6612249201e04b9db7b363c07\")>\n        home_page  = <src.pages.home_page.HomePage object at 0x7fdbd3b5ce90>\n        login_page = <src.pages.login_page.LoginPage object at 0x7fdbd3b5c5d0>\n        self       = <test_login.TestLogin object at 0x7fdbd6c42a90>\nsrc/base/base_element.py:69: in assert_error\n    current_error = self.get_text()\n        expected_error = 'The username and password could not be verified.'\n        self       = <src.base.base_element.BaseElement object at 0x7fdbd3b5f650>\n        server_error = 'An internal error has occurred and has been logged.'\nsrc/base/base_element.py:37: in get_text\n    element = self.assert_element()\n        self       = <src.base.base_element.BaseElement object at 0x7fdbd3b5f650>\nsrc/base/base_element.py:16: in assert_element\n    self.wait.until(EC.presence_of_element_located((\"xpath\", self.xpath)))\n        clickable  = False\n        return_many = False\n        self       = <src.base.base_element.BaseElement object at 0x7fdbd3b5f650>\n../local/lib/python3.11/site-packages/selenium/webdriver/support/wait.py:101: in until\n    raise TimeoutException(message, screen, stacktrace)\nE   selenium.common.exceptions.TimeoutException: Message:\n        end_time   = 393.453500605\n        message    = ''\n        method     = <function presence_of_element_located.<locals>._predicate at 0x7fdbd6c21e40>\n        screen     = None\n        self       = <selenium.webdriver.support.wait.WebDriverWait (session=\"a23ea4b6612249201e04b9db7b363c07\")>\n        stacktrace = None",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "Health check request",
    "time" : {
      "start" : 1705147517847,
      "stop" : 1705147518594,
      "duration" : 747
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "Initialize driver",
    "time" : {
      "start" : 1705147721292,
      "stop" : 1705147722131,
      "duration" : 839
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "_session_faker",
    "time" : {
      "start" : 1705147517826,
      "stop" : 1705147517847,
      "duration" : 21
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.TimeoutException: Message:",
    "statusTrace" : "tests/core_features/test_login.py:69: in test_login_with_invalid_username\n    login_page.error_text.assert_error(\"The username and password could not be verified.\")\n        driver     = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"a23ea4b6612249201e04b9db7b363c07\")>\n        home_page  = <src.pages.home_page.HomePage object at 0x7fdbd3b5ce90>\n        login_page = <src.pages.login_page.LoginPage object at 0x7fdbd3b5c5d0>\n        self       = <test_login.TestLogin object at 0x7fdbd6c42a90>\nsrc/base/base_element.py:69: in assert_error\n    current_error = self.get_text()\n        expected_error = 'The username and password could not be verified.'\n        self       = <src.base.base_element.BaseElement object at 0x7fdbd3b5f650>\n        server_error = 'An internal error has occurred and has been logged.'\nsrc/base/base_element.py:37: in get_text\n    element = self.assert_element()\n        self       = <src.base.base_element.BaseElement object at 0x7fdbd3b5f650>\nsrc/base/base_element.py:16: in assert_element\n    self.wait.until(EC.presence_of_element_located((\"xpath\", self.xpath)))\n        clickable  = False\n        return_many = False\n        self       = <src.base.base_element.BaseElement object at 0x7fdbd3b5f650>\n../local/lib/python3.11/site-packages/selenium/webdriver/support/wait.py:101: in until\n    raise TimeoutException(message, screen, stacktrace)\nE   selenium.common.exceptions.TimeoutException: Message:\n        end_time   = 393.453500605\n        message    = ''\n        method     = <function presence_of_element_located.<locals>._predicate at 0x7fdbd6c21e40>\n        screen     = None\n        self       = <selenium.webdriver.support.wait.WebDriverWait (session=\"a23ea4b6612249201e04b9db7b363c07\")>\n        stacktrace = None",
    "steps" : [ {
      "name" : "Navigate to Home page",
      "time" : {
        "start" : 1705147722132,
        "stop" : 1705147722870,
        "duration" : 738
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "Fill in valid password, but invalid username",
      "time" : {
        "start" : 1705147722870,
        "stop" : 1705147723031,
        "duration" : 161
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "Log in",
      "time" : {
        "start" : 1705147723031,
        "stop" : 1705147724027,
        "duration" : 996
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "Check error message is displayed",
      "time" : {
        "start" : 1705147724027,
        "stop" : 1705147739232,
        "duration" : 15205
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.TimeoutException: Message: \n\n",
      "statusTrace" : "  File \"/usr/workspace/tests/core_features/test_login.py\", line 69, in test_login_with_invalid_username\n    login_page.error_text.assert_error(\"The username and password could not be verified.\")\n  File \"/usr/workspace/src/base/base_element.py\", line 69, in assert_error\n    current_error = self.get_text()\n                    ^^^^^^^^^^^^^^^\n  File \"/usr/workspace/src/base/base_element.py\", line 37, in get_text\n    element = self.assert_element()\n              ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/workspace/src/base/base_element.py\", line 16, in assert_element\n    self.wait.until(EC.presence_of_element_located((\"xpath\", self.xpath)))\n  File \"/usr/local/lib/python3.11/site-packages/selenium/webdriver/support/wait.py\", line 101, in until\n    raise TimeoutException(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 4,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ {
    "name" : "Initialize driver::0",
    "time" : {
      "start" : 1705147739238,
      "stop" : 1705147739295,
      "duration" : 57
    },
    "status" : "passed",
    "steps" : [ {
      "name" : "Terminate driver",
      "time" : {
        "start" : 1705147739238,
        "stop" : 1705147739295,
        "duration" : 57
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "PARA-15240: User registration and authentication"
  }, {
    "name" : "feature",
    "value" : "PARA-15261: User login"
  }, {
    "name" : "severity",
    "value" : "Minor"
  }, {
    "name" : "parentSuite",
    "value" : "tests.core_features"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "subSuite",
    "value" : "TestLogin"
  }, {
    "name" : "host",
    "value" : "fdd3900bcbbf"
  }, {
    "name" : "thread",
    "value" : "1-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.core_features.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "minor",
    "retries" : [ {
      "uid" : "658407f9f4d0ffa8",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.TimeoutException: Message:",
      "time" : {
        "start" : 1705147704267,
        "stop" : 1705147721227,
        "duration" : 16960
      }
    }, {
      "uid" : "ab02803e851e65c",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.TimeoutException: Message:",
      "time" : {
        "start" : 1705147685894,
        "stop" : 1705147703363,
        "duration" : 17469
      }
    }, {
      "uid" : "a37b2f5105b4b942",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.TimeoutException: Message:",
      "time" : {
        "start" : 1705147667871,
        "stop" : 1705147684991,
        "duration" : 17120
      }
    } ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 1,
        "skipped" : 7,
        "passed" : 1,
        "unknown" : 0,
        "total" : 9
      },
      "items" : [ {
        "uid" : "2633b716cdc927f5",
        "status" : "passed",
        "time" : {
          "start" : 1705016482612,
          "stop" : 1705016483964,
          "duration" : 1352
        }
      }, {
        "uid" : "8b9cb9084df2ea16",
        "status" : "skipped",
        "statusDetails" : "XFAIL reason: Known server-side issue\n\n_pytest.outcomes.XFailed: Known server-side issue",
        "time" : {
          "start" : 1704913008756,
          "stop" : 1704913009802,
          "duration" : 1046
        }
      }, {
        "uid" : "82ed04e69ffff1b4",
        "status" : "skipped",
        "statusDetails" : "XFAIL reason: Health check failed with status code 502\n\n_pytest.outcomes.XFailed: Health check failed with status code 502",
        "time" : {
          "start" : 1704908682727,
          "stop" : 1704908682727,
          "duration" : 0
        }
      }, {
        "uid" : "4450358ad6895ac5",
        "status" : "skipped",
        "statusDetails" : "XFAIL reason: Known server-side issue\n\n_pytest.outcomes.XFailed: Known server-side issue",
        "time" : {
          "start" : 1704874972419,
          "stop" : 1704874973871,
          "duration" : 1452
        }
      }, {
        "uid" : "626f0d73e976d6c2",
        "status" : "skipped",
        "statusDetails" : "XFAIL reason: Known server-side issue\n\n_pytest.outcomes.XFailed: Known server-side issue",
        "time" : {
          "start" : 1704839546391,
          "stop" : 1704839547678,
          "duration" : 1287
        }
      }, {
        "uid" : "8b2995c1d1a4e4b5",
        "status" : "skipped",
        "statusDetails" : "XFAIL reason: Known server-side issue\n\n_pytest.outcomes.XFailed: Known server-side issue",
        "time" : {
          "start" : 1704789360100,
          "stop" : 1704789361271,
          "duration" : 1171
        }
      }, {
        "uid" : "e0e21325e73abf2c",
        "status" : "skipped",
        "statusDetails" : "XFAIL reason: Known server-side issue\n\n_pytest.outcomes.XFailed: Known server-side issue",
        "time" : {
          "start" : 1704759030280,
          "stop" : 1704759031332,
          "duration" : 1052
        }
      }, {
        "uid" : "5e4d1b792a3fc697",
        "status" : "skipped",
        "statusDetails" : "XFAIL reason: Known server-side issue\n\n_pytest.outcomes.XFailed: Known server-side issue",
        "time" : {
          "start" : 1704756570957,
          "stop" : 1704756572424,
          "duration" : 1467
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "f112a86e48f5a304.json",
  "parameterValues" : [ ]
}